### ISSUE TITLE
Add service.rawConfig

### ISSUE THREAD

**Issue by lunik1** [hercules-ci/arion#110]
I think it would be helpful to have a `sevice.rawConfig` to act as a low-level fallback for when service options have not yet been modelled (much like `image.rawConfig`). E.g. currently I need the unmodeled `dns` option (which can't be done via `image.rawConfig` as far as I can make out) so I could do something like:

```nix
my-service = {
    service = {
        container_name = "my-sevice";
        image = "example/image";
        rawConfig = { dns = [  "8.8.8.8" "1.1.1.1" ]; };
    };
};
```

**Comment by roberth** [comment]
This functionality exists as [`services.<name>.out.service`](https://docs.hercules-ci.com/arion/options/#_services_name_out_service).
It can be renamed. Also adding an option is easy. Here's a recent addition 38048ada2c4bcc70edb811992c879ee46de88068.

**Comment by lunik1** [comment]
Ah I missed that, thanks for the pointer. I'll look at adding the dns option.

**Comment by lunik1** [comment]
I've had a go at #111
