### ISSUE TITLE
Using arion and docker on the same host

### ISSUE THREAD

**Issue by lunik1** [hercules-ci/arion#121]
I have a machine with a mix of docker-compose and arion stacks. Previously this was not an issue as both used docker, but now that podman is required for NixOS-based containers I am not clear how to have both on the same host. I can't set `virtualisation.docker.enable` and `virtualisation.podman.dockerSocket.enable`. Will setting only the latter still allow my existing docker containers to function correctly?

**Comment by roberth** [comment]
Simultaneous Docker and Podman should run just fine. 

If you still need docker as the backend for some containers, you can leave the default `virtualisation.podman.dockerSocket.enable = false;`. Then, for your arion-based projects you can then use environment variable `DOCKER_HOST=unix:///run/podman/podman.sock` to select Podman.

**Comment by lunik1** [comment]
Seems to be working for me, thanks for the pointers!
