### ISSUE TITLE
Use arion with NixOS configuration to start a service automatically?

### ISSUE THREAD

**Issue by winston0410** [hercules-ci/arion#138]
Sorry I know this is not a technical issue but rather usage question, but I cannot find a better place to ask for arion. I will close this or contribute to the documentation based on this if possible.

I have the following questions right now:

- Right now the doc has mentioned using [`runArion`](https://docs.hercules-ci.com/hercules-ci-effects/reference/nix-functions/runarion/) for deployment, is it deploying the containers only? Does that mean that I can use that in an non NixOS environment?

- Is it possible to use arion as an NixOS module, that we can declare [something like this](https://nixos.wiki/wiki/NixOS_Containers) and auto-start on generation change?

**Comment by roberth** [comment]
> * Right now the doc has mentioned using [`runArion`](https://docs.hercules-ci.com/hercules-ci-effects/reference/nix-functions/runarion/) for deployment, is it deploying the containers only? Does that mean that I can use that in an non NixOS environment?

That is correct. Everything happens through the Docker socket; no Nix required on the target.

> * Is it possible to use arion as an NixOS module, that we can declare [something like this](https://nixos.wiki/wiki/NixOS_Containers) and auto-start on generation change?

Such a module hasn't been written yet but it's definitely feasible. It could even prebuild the project to avoid having to copy `.nix` files etc, just like the effect [does](https://github.com/hercules-ci/hercules-ci-effects/blob/783a12787ddc09af53fd01a2e6ba40cb8d48702d/effects/arion/run-arion.nix#L60).

So I guess the question for you is whether you always want to deploy your containers simultaneously with your host OS.

**Comment by roberth** [comment]
See https://docs.hercules-ci.com/arion/deployment/#_nixos_module

**Comment by winston0410** [comment]
Nice addition for Arion!
