### ISSUE TITLE
Referring to <name>.nixos.configuration in <name>.service

### ISSUE THREAD

**Issue by lunik1** [hercules-ci/arion#143]
The following configuration 

```nix
{ config, lib, pkgs, ... }:

{
  config = {
    project.name = "Træfik example";

    services = {
      traefik = { config, pkgs, ... }: {
        nixos = {
          configuration = {
            services.traefik = {
              enable = true;
              entryPoints = {
                websecure.address = ":443";
                web.address = ":80";
              };
            };
          };
        };
        service = {
          container_name = "traefik";
          volumes = [ "/opt/traefik:${config.nixos.configuration.services.traefik.dataDir}" ];
        };
      };
    };
  };
}
```
gives the error
```
error: value is a list while a set was expected

       at arion-compose.nix:22:39:

           21|           container_name = "traefik";
           22|           volumes = [ "/opt/traefik:${config.nixos.configuration.services.traefik.dataDir}" ];
             |                                       ^
           23|         };
(use '--show-trace' to show detailed location information)
```

How can I properly refer to the final nixos configuration in the associated service block? The (what I think is) obvious solution above doesn't seem to work as `nixos.configuration` is a list rather than a set/module.

**Comment by roberth** [comment]
For now, you need to use [`nixos.evaluatedConfig`](https://docs.hercules-ci.com/arion/options/#_services_name_nixos_evaluatedconfig).

This can be improved (and simplified internally) in a couple of months, when `evalModules` exposes a module system _type_ in all supported NixOS releases. https://github.com/NixOS/nixpkgs/pull/143207

**Comment by lunik1** [comment]
Yes that's just what I need. Thanks for the fast response!
