### ISSUE TITLE
How to import a NixOS moulde in arion-compose.nix?

### ISSUE THREAD

**Issue by pandaman64** [hercules-ci/arion#144]
Hi! I'd like to import my NixOS module in a service in `arion-compose.nix`, but I couldn't figure out a way to do it.
In [the document](https://docs.hercules-ci.com/arion/options/#_services_name_nixos_configuration), `services.<name>.nixos.configuration` can accept a list of configuration, and I thought it is possible to import the NixOS module in the list.
However, when I used a list (even an empty list) for `services.<name>.nixos.configuration`, `arion build` failed as follows:
```console
$ arion build
error: Module imports can't be nested lists. Perhaps you meant to remove one level of lists? Definitions:
       - In `<unknown-file>':
           [
             <function>
             <function>
           ]
(use '--show-trace' to show detailed location information)
```

I'm using this `arion-compose.nix` file: https://github.com/pandaman64/satysfi-playground/blob/b57bfd6f3d0bdbd77a6cbb7ac8b7d8547f6cd4bf/arion-compose.nix#L38

Thanks!

**Comment by roberth** [comment]
Off the top of my head, this should work:

```nix
services.<name>.nixos.configuration = { ... }: {
  imports = [
    ./foo.nix
  ];
  
  # ... other nixos defs, like ...
  services.satysfi-playground = {
    # ...
  };
}
```

**Comment by pandaman64** [comment]
It worked. Thanks!
