### ISSUE TITLE
fails to update on NixOS 23.11 due to nix-store version

### ISSUE THREAD

**Issue by jalbstmeijer** [hercules-ci/arion#234]
Getting this error when cules-ci-cnix-store-0.3.4.0 is build;

CallStack (from HasCallStack):
  withMetadata, called at libraries/Cabal/Cabal/src/Distribution/Simple/Utils.hs:370:14 in Cabal-3.8.1.0:Distribution.Simple.Utils
Error: Setup: The pkg-config package 'nix-store' version >=2.4 && <2.17 is
required but the version installed on the system is version 2.18.1

**Comment by roberth** [comment]
The arion package does not use the hercules-ci-cnix-* packages, so this error is probably the result of trying to use an outdated hercules-ci-agent or cachix expression with a newer Nixpkgs.

Assuming you got this from `nixos-rebuild` or perhaps the Nix command line interface, it should print the paths of derivations that depend on this failed build, and that should give you information about why this build was attempted.

If you're using a flake like hercules-ci-agent or cachix, this should be solvable by updating your flake inputs.

**Comment by jalbstmeijer** [comment]
@roberth thanks for the feedback. Still not sure how to fix it, bit I will try it on general nixos support channel

**Comment by roberth** [comment]
Most likely this was a cachix build failure on the NixOS 23.11 release branch, which will be fixed in https://github.com/NixOS/nixpkgs/pull/294579.
