### ISSUE TITLE
passing non-pkgs stuff like flake `inputs` to container

### ISSUE THREAD

**Issue by KiaraGrouwstra** [hercules-ci/arion#247]
given a flake-based way of working, it would be nice to pass more stuff to containerized machines than just `pkgs`, such as `inputs`, so as to also grab e.g. nix modules.
while i've found one can technically smuggle stuff thru what arion presumes to be just `pkgs`, i... am not sure i'm particularly proud of that idea.
would anyone perhaps have found a nicer way to do this?

**Comment by KiaraGrouwstra** [comment]
bit hacky, but i got this to work using a few different approaches:

```nix
# flake.nix

  outputs = { nixpkgs, ... }@inputs: let
    pkgs = nixpkgs.legacyPackages.x86_64-linux;
  in {
    inherit inputs pkgs;
  };
```

then either separating them but having arion confusingly call the wrapper `pkgs`:

```nix
# arion-pkgs.nix
let
  flake = builtins.getFlake (toString ./.);
  inherit (flake) inputs pkgs;
in
  {
    # bits i wanna pass to my containers
    inherit inputs pkgs;
    # stuff arion wants to see me return
    inherit (pkgs) lib writeText nix nixos path dockerTools closureInfo runCommand;
  }
```

```nix
# arion-compose.nix
{
  # smuggling in `inputs` thru `pkgs`: https://github.com/hercules-ci/arion/issues/247
  pkgs,
  ...
}:
{
  project.name = "nixos container";
  services.webserver = {
    nixos = {
      useSystemd = true;
      configuration = import ./servers/manual/configuration.nix pkgs;
    };
    service = ...;
  };
}
```

or instead hide your other stuff like `inputs` in `pkgs`:

```nix
# arion-pkgs.nix

let
  flake = builtins.getFlake (toString ./.);
  inherit (flake) inputs pkgs;
in
  pkgs // { inherit inputs; }
```

```nix
# arion-compose.nix
{
  # smuggling in `inputs` thru `pkgs`: https://github.com/hercules-ci/arion/issues/247
  pkgs,
  ...
}:
let
  inherit (pkgs) lib inputs;
in
{
  project.name = "nixos container";
  services.webserver = {
    nixos = {
      useSystemd = true;
      configuration = import ./servers/manual/configuration.nix { inherit lib pkgs inputs; };
    };
    service = ...;
  };
}
```

**Comment by KiaraGrouwstra** [comment]
looks like `pkgs` gets passed [by `--arg pkgs ./arion-pkgs.nix`](https://github.com/hercules-ci/arion/blob/main/src/haskell/lib/Arion/Nix.hs#L157-L159), so facilitating custom args may involve passing additional stuff.

open questions there seem to include:

- how to just pass it an arbitrary attrset of additional parameters from the nix module
- whether that could facilitate passing e.g. functions, or if that'd run into issues say serializing

**Comment by KiaraGrouwstra** [comment]
actually, a workaround seems:

```
let
  inherit (builtins.getFlake (toString ./.)) inputs;
in 
{
  imports = [
    (import ./module.nix { inherit inputs; })
  ];
}
```

**Comment by jefdaj** [comment]
Thanks! This saved me a ton of time.

Maybe it should go in the documentation somewhere? I could learn how to add it if that helps.

Also I came up with a variation that seems slightly cleaner to me, but that's debatable.

```nix
# arion-pkgs.nix
let
  flake = builtins.getFlake (toString ./.);
  inherit (flake) pkgs;
in pkgs // {
  # smuggle in the entire flake
  # see https://github.com/hercules-ci/arion/issues/247
  inherit flake;
}
``` 

```nix
# arion-compose.nix
{ pkgs, ...}:

let
  # smuggle flake in via pkgs
  # see https://github.com/hercules-ci/arion/issues/247
  inherit (pkgs) flake;
  ...
    image.contents = [
      # access any flake attr
      flake.packages.x86_64-linux.<mypkg>
    ];
```
