### ISSUE TITLE
Support image.contents (files outside store) with useHostStore

### ISSUE THREAD

**Issue by roberth** [hercules-ci/arion#27]
useHostStore currently sets the image to something with /bin/sh and /usr/bin/env symlinks, thus ignoring image.contents.

This can be implemented with a wrapper script (like entrypoint), but that may not run as root.
Otherwise, we should probably generate a small layer anyway with a symlink farm or the single derivation.

**Comment by spinus** [comment]
would be nice to have at least an assert for that before feature is implemented.
