### ISSUE TITLE
DRY docs using build step?

### ISSUE THREAD

**Issue by roberth** [hercules-ci/arion#41]
Couldn't find a method to inline with asciidoctor alone, but the following produces an asciidoc

    asciidoctor -b docbook5 -o - index.adoc | pandoc --from docbook --to asciidoc

- [ ] is the quality ok?
- [ ] command to build and overwrite README
- [ ] CI for the README file
- [ ] pre-commit hook

**Comment by domenkozar** [comment]
I think we should have proper documentation site with #10  and just link it from README, keeping the two in sync will be just too much pain.

For inline do `asciidoctor -d inline index.adoc -o -`

**Comment by roberth** [comment]
:+1:
