### ISSUE TITLE
environment.systemPackages ignored

### ISSUE THREAD

**Issue by paumr** [hercules-ci/arion#65]
```nix
{ pkgs, ... }:
{
  docker-compose.services = {
    webserver = { config, pkgs, ... }: {
      nixos.configuration = {config, pkgs, ...}: {
          boot.isContainer = true;
          environment.systemPackages = with pkgs; [
            tree
          ];
      };
      service = {
        command = [  "sh" "-c" "tree" ];
        useHostStore = true;
      };
    };
  };
}
```

Since `environment.systemPackages` seems to be ignored, what's the recommended way to manage dependencies?

**Comment by domenkozar** [comment]
See #40

**Comment by roberth** [comment]
There's multiple ways one might make use of NixOS configuration to create a docker image. You can run your service as a NixOS service and enable `nixos.useSystemd` to set the docker command to systemd. That's the most predictable way to use NixOS. Alternatively you can wire up `service.command` or `image.command` like [this](https://github.com/hercules-ci/arion/blob/master/examples/nixos-unit/arion-compose.nix) for example.

If you're not using NixOS by calling its init systemd, there's always a chance that you need something that's normally taken care of by NixOS, like installing certain packages or background services (such as cleaning tmp, reaping zombies etc etc).

So it really depends on your use case. I currently recommend `nixos.useSystemd` for most cases but if you need to deploy lightweight images, you'll have to use the `image` options to do some things manually instead. Proper images are a recent addition to Arion, so your mileage may vary with that feature.

**Comment by paumr** [comment]
Alright, thanks!

If someone runs into a similar issue, here's a working example:
```nix
{ pkgs, ... }:
{
  docker-compose.services = {
    webserver = { config, pkgs, ... }: {
      nixos.configuration = {config, pkgs, ...}: {
        boot.isContainer = true;
        environment.systemPackages = with pkgs; [
          # will be evaluated if service.command isn't set
          tree
        ];
        system.build.someEntryFun = pkgs.writeScript "someEntryFun" ''
          #!${pkgs.bash}/bin/bash
          ${pkgs.cowsay}/bin/cowsay "dependencies in this script are fetched automatically"
        '';
      };
      nixos.useSystemd = true;
      service = {
        command = [ config.nixos.build.someEntryFun ];
        useHostStore = true;
      };
    };
  };
}
```
if `nixos.command` is commented out calling `docker exec -it <some-hash> tree` will be possible.
