### ISSUE TITLE
Arion.Nix evaluateComposition "matches an example" test failure (on unsupported Mac OS)

### ISSUE THREAD

**Issue by jbmusso** [hercules-ci/arion#83]
Hello, I'm currently experimenting with Arion on Mac OS X (10.14.5). Although not listed as a supported OS in the doc, I'm giving it a shot.

Using nix, I'm currently getting the following error when building. I'm unsure what could go wrong in this Haskell test on this platform, but maybe this issue can help troubleshoot something else.

```
assertion failed at /nix/store/f7rbfswfrx81y3v86i7gykj0js4pxrnh-vyqishq17q64pxfc6r627d42xddilh9z-source/pkgs/os-specific/linux/kernel/generic.nix:56:1

Arion.Nix
  evaluateComposition
    matches an example FAILED [1]

Failures:

  src/haskell/test/Arion/NixSpec.hs:16:41: 
  1) Arion.Nix.evaluateComposition matches an example
       uncaught exception: ExitCode
       ExitFailure 1

  To rerun use: --match "/Arion.Nix/evaluateComposition/matches an example/"

Randomized with seed 190610212

Finished in 0.4093 seconds
1 example, 1 failure

Test suite arion-unit-tests: FAIL
Test suite logged to: dist/test/arion-compose-0.1.0.0-arion-unit-tests.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for '/nix/store/c7iia08jiab758w51fg3s7sl401achq6-arion-0.1.0.0.drv' failed with exit code 1
error: build of '/nix/store/c7iia08jiab758w51fg3s7sl401achq6-arion-0.1.0.0.drv' failed
```

Relevant part of nix derivation:

```nix
pkgs.fetchFromGitHub {
    owner = "hercules-ci";
    repo = "arion";
    rev = "v0.1.0.0";
    sha256 = "021biqdlmbh746ji3m35bhwag68p3qlnxrwf8iaw3sz552j9dcfj";
  }
```

**Comment by roberth** [comment]
It seems to try to build NixOS for darwin. That's a bit too ambitious ;)

The fix is to add `system = "x86_64-linux"` somewhere. The tests do not need to build actual derivations; just evaluate things, so that should make it work.

You can ignore the unit tests for now if you want to try it with macOS. I don't think there's anything in the Haskell program that's particularly platform-dependent, except of course in the Nix bits.

**Comment by roberth** [comment]
`arion` is now on Nixpkgs master.
The unit tests are disabled there for simplicity (avoiding a Nixpkgs source dependency and associated hassle/churn).

**Comment by jbmusso** [comment]
Ha! I didn't realize that it was trying to do that much :).
Thanks for mentioning Nixpkgs master, I'll experiment from there.

(Cross-linking Nixpkgs arion 0.1.0.0 PR for reference, if anyone encounters the same issue: https://github.com/NixOS/nixpkgs/pull/71092)
